- name: Create Sites and Themes
  shell: >
    {{ COMMON_BIN_DIR }}/python.edxapp {{ COMMON_BIN_DIR }}/manage.edxapp lms --settings={{ COMMON_EDXAPP_SETTINGS }}
    create_sites_and_configurations --dns-name {{ dns_name }}
  become_user: "{{ edxapp_user }}"
  environment: "{{ edxapp_environment }}"

- name: "display compile assets command"
  debug:
    msg: "{{ COMMON_BIN_DIR }}/edxapp-update-assets-{{ item }}"
  with_items: "{{ service_variants_enabled }}"
